### ISSUE TITLE
Focal length  and image centre calculation

### ISSUE THREAD

**Issue by sowmiyadharmalingam86** [tobybreckon/stereo-disparity#1]
camera_focal_length_px = 399.9745178222656  # focal length in pixels
camera_focal_length_m = 4.8 / 1000          # focal length in metres (4.8 mm)
stereo_camera_baseline_m = 0.2090607502     # camera baseline in metres

image_centre_h = 262.0;
image_centre_w = 474.5;

How do you calculate the above  listed parameters?

**Comment by tobybreckon** [comment]
They come from the factory calibration of the camera - or calibrate using stereo / calibation code in https://github.com/tobybreckon/python-examples-cv (stereo_sgbm.py / calibrate_camera.py)

**Comment by sowmiyadharmalingam86** [comment]
> They come from the factory calibration of the camera - or calibrate using stereo / calibation code in https://github.com/tobybreckon/python-examples-cv (stereo_sgbm.py / calibrate_camera.py)
   
Thank you for your  prompt reply. I got to under stand the cx, cy values. However in regard to focal length we have two values fx, fy for both left and right cameras. Among fx and fy which value  should we consider from which camera.Kindly help me out to understand this.

**Comment by tobybreckon** [comment]
See - https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html

I'd recommend Multiple View Geometry by Hartley / Zisserman.

**Comment by sowmiyadharmalingam86** [comment]
> See - https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html
> 
> I'd recommend Multiple View Geometry by Hartley / Zisserman.

Thank you
